version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto"
    volumes:
      - ${HOME}/config/mosquitto:/mosquitto/config
    restart: unless-stopped
    privileged: true
    network_mode: host
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${HOME}/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  grafana:
    container_name: grafana
    image: "grafana/grafana:latest"
    volumes:
      - ${HOME}/config/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    volumes:
      - ${HOME}/config/influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  node-red:
    container_name: node-red
    image: "nodered/node-red:latest"
    volumes:
      - ${HOME}/config/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    volumes:
      - ${HOME}/config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  evcc:
    image: evcc/evcc:latest
    container_name: evcc
    network_mode: host
    volumes:
      - /home/lieven/workspace/iot-server/evcc:/root/.evcc
      - /home/lieven/workspace/iot-server/evcc/evcc.yaml:/etc/evcc.yaml  # optional, if using file config
    restart: unless-stopped
