M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Fri 13 Feb 2026 04:58:48 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-13T16:58:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X116.84Y-73.66
X116.84Y-119.38
X195.58Y-73.66
X195.58Y-119.38
M30
