services:
  evcc:
    image: evcc/evcc:latest
    container_name: evcc
    network_mode: host
    volumes:
      - /home/lieven/workspace/iot-server/evcc:/root/.evcc
      - /home/lieven/workspace/iot-server/evcc/evcc.yaml:/etc/evcc.yaml  # optional, if using file config
    restart: unless-stopped