M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sat 07 Mar 2026 12:40:20 AM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-07T00:40:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X116.84Y-73.66
X116.84Y-119.38
X195.58Y-73.66
X195.58Y-119.38
M30
