esphome:
  name: shaker1

<<: !include limero.yaml

# Enable logging
logger:

ota:



esp8266:
  board: nodemcuv2
  framework:
    version: recommended

mqtt:
  broker: limero.ddns.net
  port: 1883 

status_led:
  pin: GPIO2

sensor:
  - platform: mqtt_subscribe
    name: "Treeshaker1"
    id: shaker1
    topic: dst/esp2/shaker/shake