esphome:
  name: esp8266_pulse

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

<<: !include limero.yaml
# Enable logging
logger:

ota:

mqtt:
  broker: limero.ddns.net
  port: 1883 

output:
  - platform: gpio
    pin: GPIO16
    id: mister_relay

switch:
  - platform: template
    name: "Mister"
    id: mister_enable
    optimistic: on

interval:
  - interval: 20sec
    then:
      if:
        condition:
          switch.is_on: mister_enable
        then:
          - output.turn_on: mister_relay
          - delay: 500ms
          - output.turn_off: mister_relay
