version: '3'
services:
  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    volumes:
      - ${HOME}/config/influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

